-- Create AI Feedback Table
create table if not exists public.ai_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  advice_text text not null,
  rating text not null check (rating in ('like', 'dislike')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.ai_feedback enable row level security;

-- Policies
create policy "Users can insert their own feedback" on public.ai_feedback for insert with check (auth.uid() = user_id);
create policy "Users can view their own feedback" on public.ai_feedback for select using (auth.uid() = user_id);
