-- Create Budgets Table
create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  category text not null,
  amount_limit numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, category) -- One budget per category per user
);

-- Enable RLS
alter table public.budgets enable row level security;

-- Policies for Budgets
create policy "Users can view their own budgets" on public.budgets for select using (auth.uid() = user_id);
create policy "Users can insert their own budgets" on public.budgets for insert with check (auth.uid() = user_id);
create policy "Users can update their own budgets" on public.budgets for update using (auth.uid() = user_id);
create policy "Users can delete their own budgets" on public.budgets for delete using (auth.uid() = user_id);
